services:
  - type: web
    name: occupancy-estimator
    env: python
    plan: free
    buildCommand: pip install -r truck_app/requirements.txt
    startCommand: PYTHONPATH=./truck_app gunicorn app:app --chdir truck_app --bind 0.0.0.0:10000
