services:
  - type: web
    name: occupancy-estimator
    env: python
    plan: free
    buildCommand: pip install -r truck_app/requirements.txt
    startCommand: PYTHONPATH=. gunicorn truck_app.app:app --bind 0.0.0.0:10000
